[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "custom art gesture clerk lab nice paddle omit pause absorb orange tunnel amazing response animal fish legal bulb quality claim mention speed awake talk"
